#############################################################
# R interface script for calling and testing STAN model for
# Single-Tau approximation model
#############################################################

#### Necessary libraries ####
library(rstan) # STAN
library(bayesplot) # for stan diagnostics plots
library(GGally) # for prettier plots
library(readxl) # for getting excel data into R
library(latex2exp) # for plot
library(loo) # diagnostic library to extract log likelihood
library(shinystan) # (optional) diagnostics overview


options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

### Recipe for changing between amount of time intervals ###
# Change variable n
# Add/remove additional t_switch_n and x_n from t_switch and x_hat
# Change alpha vector in Stan Model call
# Comment out/in additional t_switch_n_stan and x_n_stan from
# Add/remove additional t_switch_n_stan and x_n_stan from t_switch_stan and x_hat_stan
###

#### Declaration of artificial/testing Values ####
t <- 1000
n <- 5
tau <- 50
sigma_x <- 0.01
x_hat_one <- 1
x_hat_two <- 3
x_hat_three <- 5
x_hat_four <- 7
x_hat_five <- 9
t_switch_one <- 100
t_switch_two <- 300
t_switch_three <- 500
t_switch_four <- 700
t_switch_five <- 900

source("sampling.R")
x_hat <- c(x_hat_one, x_hat_two, x_hat_three, x_hat_four, x_hat_five)
t_switch <- c(t_switch_one, t_switch_two, t_switch_three, t_switch_four, t)
result <- result_fit(n, t, tau, sigma_x, x_hat, t_switch)

#### Stan Model & Fit ####
model <- stan_model("model.stan")
fit <- sampling(
    model,
    list(t = t, x = result[1:t], N = n, alpha = c(3, 3, 3, 3, 3)),
    iter = 4000, chains = 2
)

print(fit)

#### Extracting the data from Stan ####
params <- extract(fit) # parameters found by stan
inits <- get_inits(fit) # initial values generated by stan
summary <- summary(fit) # summary to print to pdf
df <- data.frame(params)

ggpairs(df, aes(alpha = 0.01))
np <- nuts_params(fit)

posterior <- as.data.frame(unlist(fit))
tau_stan <- mean(posterior$tau)
sigma_x_stan <- mean(posterior$sigma_x)
x_one_stan <- mean(posterior$"x_hat[1]")
x_two_stan <- mean(posterior$"x_hat[2]")
x_three_stan <- mean(posterior$"x_hat[3]")
x_four_stan <- mean(posterior$"x_hat[4]")
x_five_stan <- mean(posterior$"x_hat[5]")
t_switch_one_stan <- mean(posterior$"t_sw[1]")
t_switch_two_stan <- mean(posterior$"t_sw[2]")
t_switch_three_stan <- mean(posterior$"t_sw[3]")
t_switch_four_stan <- mean(posterior$"t_sw[4]")
t_switch_five_stan <- mean(posterior$"t_sw[5]")

x_hat_stan <- c(x_one_stan, x_two_stan, x_three_stan, x_four_stan, x_five_stan)
t_switch_stan <- c(t_switch_one_stan, t_switch_two_stan, t_switch_three_stan, t_switch_four_stan, t_switch_five_stan)
result_stan <- result_fit(n, t, tau_stan, sigma_x_stan, x_hat_stan, t_switch_stan)

data_stan <- data.frame(seq(t) - 1, result[1:t], result_stan[1:t])
data_melt_stan <- melt(data_stan,
    id.vars = "seq.t....1",
    variable.name = "Result",
    value.name = "Concentration"
)
#### Creating Plots ####

### Creating Timeseries plot ###
p <- ggplot(
    data = data_melt_stan,
    aes(x = seq.t....1, y = Concentration, group = Result, colour = Result)
)

plot <- p + geom_line() +
    xlab("Time (s)") +
    ylab(TeX("Tension $\\left(N/m\\right)$")) +
    scale_x_continuous(
        breaks = round(seq(min(data_stan$seq.t....1), max(data_stan$seq.t....1), by = 150), 0)
    ) +
    scale_y_continuous(
        breaks = round(
            seq(min(data_stan$result.1.t.),
                max(data_stan$result.1.t.),
                by = 1
            ), 0
        )
    ) +
    geom_vline(xintercept = result[t + 1], color = "blue", size = 0.2) +
    geom_vline(xintercept = result[t + 2], color = "blue", size = 0.2) +
    geom_vline(xintercept = result[t + 3], color = "blue", size = 0.2) +
    geom_vline(xintercept = result[t + 4], color = "blue", size = 0.2) +
    geom_vline(xintercept = result[t + 5], color = "blue", size = 0.2) +
    geom_vline(xintercept = result_stan[t + 1], color = "red", size = 0.2) +
    geom_vline(xintercept = result_stan[t + 2], color = "red", size = 0.2) +
    geom_vline(xintercept = result_stan[t + 3], color = "red", size = 0.2) +
    geom_vline(xintercept = result_stan[t + 4], color = "red", size = 0.2) +
    geom_vline(xintercept = result_stan[t + 5], color = "red", size = 0.2)


### Diagnostic Plots ###
np_subset <- subset(np, Parameter != "energy__" & Parameter != "n_leapfrog__" & Parameter != "stepsize__")
np_plot <- ggplot(
    data = np_subset,
    aes(x = Iteration, y = Value, group = Parameter, colour = Parameter)
) +
    geom_line()

### Checking, finding, comparing maximum log likelihood value ###
source("maximum_likelihood.R")
mll_mean_stan <- mean(posterior$"lp__") # Maximum Log Likelihood mean value from Stan fit
mll_mean_dummy_result <- maximum_log_likelihood(t, x_hat, t_switch, tau, sigma_x, result[1:t])
mll_mean_stan_result <- maximum_log_likelihood(t, x_hat_stan, t_switch_stan, tau_stan, sigma_x_stan, result_stan[1:t])
cat("The maximum likelihood found by STAN: ", mll_mean_stan, "\n")
cat("The maximum likelihood STAN could find: ", mll_mean_stan_result[t], "\n")
cat("The maximum likelihood found by unit test: ", mll_mean_dummy_result[t], "\n")

mll_data <- data.frame(seq(t), mll_mean_dummy_result, mll_mean_stan_result)
data_melt_mll <- melt(mll_data,
    id.vars = "seq.t.",
    variable.name = "Result",
    value.name = "Concentration"
)

mll_plot <- ggplot(
    data = data_melt_mll,
    aes(x = seq.t., y = Concentration, group = Result, colour = Result)
) +
    geom_line() +
    xlab("Time (s)") +
    ylab(TeX("Tension $\\left(N/m\\right)$"))



### Saving Plots and Data ###
pdf("results.pdf")
print(plot)
print(ggpairs(df, aes(alpha = 0.01)))
print(np_plot)
print(traceplot(fit, c("tau", "t_sw[5]", "x_hat[5]", "lp__"), inc_warmup = TRUE))
print(traceplot(fit))
print(mll_plot)
dev.off()

sink("results.txt")
print(fit_summary$summary)
sink()

### Optional Diagnostics Visualisation ###
# launch_shinystan(fit)